# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Effective Python for Data Scientists
author: Khuyen Tran
logo: img/data_simplified_icon.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: off
  exclude_patterns:
  - 'Chapter1/collections.ipynb'

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    myst_nb_number_source_lines: false
    myst_nb_metadata_key: nbf
    myst_enable_extensions:
      - replacements
      - linkify
      - substitution
      - colon_fence
      - dollarmath
      - amsmath
    myst_heading_anchors: 2
    nb_render_markdown_format: myst
    nb_render_priority:
      html:
      - "application/vnd.jupyter.widget-view+json"
      - "application/javascript"
      - "text/html"
      - "image/svg+xml"
      - "image/png"
      - "image/jpeg"
      - "text/markdown"
      - "text/latex"
      - "text/plain"

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/khuyentran1401/Efficient_Python_tricks_and_tools_for_data_scientists  # Online location of your book
  path_to_book: . # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html\#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  comments:
    utterances:
      repo: "khuyentran1401/Efficient_Python_tricks_and_tools_for_data_scientists"

launch_buttons:
  colab_url: "https://colab.research.google.com"

theme: jekyll-theme-slate
only_build_toc_files: true
